version: "3.8"
services:
  app:
    build:
      context: ./app
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:4000
      - NEXT_PUBLIC_WS_URL=http://api:4000
      - NEXT_PUBLIC_WS_URL_BROWSER=http://localhost:4000
    volumes:
      - ./app:/usr/src/app
    networks:
      - utt-net

  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=utt
    volumes:
      - ./api:/usr/src/api
    networks:
      - utt-net

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utt
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - utt-net

networks:
  utt-net:

volumes:
  mysql-data:
